import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import QueryProvider from "@/providers/QueryProvider"; // Importe o componente criado

import { ThemeProvider } from "@/providers/ThemeProvider";
import { EmailProvider } from "@/context/EmailContext";
import Header from "@/components/header/Header";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <AuthProvider>
        <EmailProvider>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <QueryProvider>
            <Header />
            {" "}
            {/* Utilize o QueryProvider aqui */}
            {children}
            <Toaster />
          </QueryProvider>
          </ThemeProvider>
        </body>
        </EmailProvider>
      </AuthProvider>
    </html>
  );
}
